package bg.tusofia.fktt.zkalev.dessertation.db.datamodel;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHOTOS.
 */
public class Photos {

    private String photo;
    private String photo_reference;
    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Photos() {
    }

    public Photos(Long id) {
        this.id = id;
    }

    public Photos(String photo, String photo_reference, Long id) {
        this.photo = photo;
        this.photo_reference = photo_reference;
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhoto_reference() {
        return photo_reference;
    }

    public void setPhoto_reference(String photo_reference) {
        this.photo_reference = photo_reference;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
