package bg.tusofia.fktt.zkalev.dessertation.db.datamodel;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PLACE.
 */
public class Place {

    private String name;
    private String phone;
    private String addres;
    private String location;
    private String reference;
    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Place() {
    }

    public Place(Long id) {
        this.id = id;
    }

    public Place(String name, String phone, String addres, String location, String reference, Long id) {
        this.name = name;
        this.phone = phone;
        this.addres = addres;
        this.location = location;
        this.reference = reference;
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddres() {
        return addres;
    }

    public void setAddres(String addres) {
        this.addres = addres;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
